version: "3.7"

services:
  krakend:
    image: devopsfaith/krakend:watch
    platform: linux/amd64
    container_name: krakend
    volumes:
      - ./configs:/etc/krakend
      - ./entrypoint.sh:/etc/krakend/entrypoint.sh
    ports:
      - "1226:1234"
      - "1227:8080"
      - "1228:8090"
    environment:
      - FC_ENABLE=1
      - APP_NAME = 'TemplrJS'
      - APP_DESCRIPTION = 'TemplrJS is the full-stack web framework built on NuxtJS, TailwindCSS, Supabase designed for edge computing to help build personal projects to small to medium size business application'
      - API_VERSION = '1.0.0.02122023'
      - APP_VERSION = '1.0.0.03222024'
      - API_BASE_PATH_DUCK_DB=https://duckdb-data-api.vercel.app
      - SUPABASE_URL=https://lztihcjfpbpkrcdtwsxg.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6dGloY2pmcGJwa3JjZHR3c3hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjcyMjA1NzIsImV4cCI6MTk4Mjc5NjU3Mn0.eNqEj4UODjXnw6DFKKwT4aXGg3drWu3WSOxhD3Y0GcY
    entrypoint: ["/bin/sh", "/etc/krakend/entrypoint.sh"] #Make sure that you have `chmod +x entrypoint.sh`
#    depends_on:
#      - jaeger
#  jaeger:
#    image: jaegertracing/all-in-one:1
#    ports:
#      - "16686:16686"
#      - "14268:14268"