name: Build and Push Docker Image

on:
  push:
    branches:
      - main # or whichever branch you'd like

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17 # specify the desired version

    - name: Compile Go for linux/amd64
      run: |
        GOOS=linux GOARCH=amd64 go build -o templrjs_server-linux-amd64

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/templrjs:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/templrjs:${{ github.sha }}
          ${{ secrets.DOCKERHUB_USERNAME }}/templrjs:build-${{ github.run_id }}

